"""Add cart and cart_items tables

Revision ID: 6bedbedf8fe0
Revises: 7ea4eb3b843f
Create Date: 2025-06-10 22:03:13.147275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bedbedf8fe0'
down_revision: Union[str, None] = '7ea4eb3b843f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
